//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 28.04.2022 17:29:58
namespace Ch.Abacus.Worx
{
    /// <summary>
    /// There are no comments for ActivitySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ActivitySingle")]
    public partial class ActivitySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Activity>
    {
        /// <summary>
        /// Initialize a new ActivitySingle object.
        /// </summary>
        public ActivitySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ActivitySingle object.
        /// </summary>
        public ActivitySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ActivitySingle object.
        /// </summary>
        public ActivitySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Activity> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Address")]
        public virtual global::Ch.Abacus.Worx.AddressSingle Address
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Address == null))
                {
                    this._Address = new global::Ch.Abacus.Worx.AddressSingle(this.Context, GetPath("Address"));
                }
                return this._Address;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Ch.Abacus.Worx.AddressSingle _Address;
    }
    /// <summary>
    /// There are no comments for Activity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ActivityKey
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ActivityKey")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Activity")]
    public partial class Activity : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Activity object.
        /// </summary>
        /// <param name="activityKey">Initial value of ActivityKey.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="done">Initial value of Done.</param>
        /// <param name="activityType">Initial value of ActivityType.</param>
        /// <param name="addressNumber">Initial value of AddressNumber.</param>
        /// <param name="address">Initial value of Address.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Activity CreateActivity(global::System.Guid activityKey, 
                    string description, 
                    bool done, 
                    string activityType, 
                    long addressNumber, 
                    global::Ch.Abacus.Worx.Address address)
        {
            Activity activity = new Activity();
            activity.ActivityKey = activityKey;
            activity.Description = description;
            activity.Done = done;
            activity.ActivityType = activityType;
            activity.AddressNumber = addressNumber;
            if ((address == null))
            {
                throw new global::System.ArgumentNullException("address");
            }
            activity.Address = address;
            return activity;
        }
        /// <summary>
        /// There are no comments for Property ActivityKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ActivityKey")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ActivityKey is required.")]
        public virtual global::System.Guid ActivityKey
        {
            get
            {
                return this._ActivityKey;
            }
            set
            {
                this.OnActivityKeyChanging(value);
                this._ActivityKey = value;
                this.OnActivityKeyChanged();
                this.OnPropertyChanged("ActivityKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _ActivityKey;
        partial void OnActivityKeyChanging(global::System.Guid value);
        partial void OnActivityKeyChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        [global::System.ComponentModel.DataAnnotations.StringLengthAttribute(255, ErrorMessage = "Description cannot be longer than 255 characters.")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Description is required.")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Done in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Done")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Done is required.")]
        public virtual bool Done
        {
            get
            {
                return this._Done;
            }
            set
            {
                this.OnDoneChanging(value);
                this._Done = value;
                this.OnDoneChanged();
                this.OnPropertyChanged("Done");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _Done;
        partial void OnDoneChanging(bool value);
        partial void OnDoneChanged();
        /// <summary>
        /// There are no comments for Property ActivityType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ActivityType")]
        [global::System.ComponentModel.DataAnnotations.StringLengthAttribute(16, ErrorMessage = "ActivityType cannot be longer than 16 characters.")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ActivityType is required.")]
        public virtual string ActivityType
        {
            get
            {
                return this._ActivityType;
            }
            set
            {
                this.OnActivityTypeChanging(value);
                this._ActivityType = value;
                this.OnActivityTypeChanged();
                this.OnPropertyChanged("ActivityType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ActivityType;
        partial void OnActivityTypeChanging(string value);
        partial void OnActivityTypeChanged();
        /// <summary>
        /// There are no comments for Property AddressNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AddressNumber")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AddressNumber is required.")]
        public virtual long AddressNumber
        {
            get
            {
                return this._AddressNumber;
            }
            set
            {
                this.OnAddressNumberChanging(value);
                this._AddressNumber = value;
                this.OnAddressNumberChanged();
                this.OnPropertyChanged("AddressNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _AddressNumber;
        partial void OnAddressNumberChanging(long value);
        partial void OnAddressNumberChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Address")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Address is required.")]
        public virtual global::Ch.Abacus.Worx.Address Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Ch.Abacus.Worx.Address _Address;
        partial void OnAddressChanging(global::Ch.Abacus.Worx.Address value);
        partial void OnAddressChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// A subject which can either be an organisation or a natural person
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AddressSingle")]
    public partial class AddressSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Address>
    {
        /// <summary>
        /// Initialize a new AddressSingle object.
        /// </summary>
        public AddressSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AddressSingle object.
        /// </summary>
        public AddressSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AddressSingle object.
        /// </summary>
        public AddressSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Address> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Activities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Activities")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Ch.Abacus.Worx.Activity> Activities
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Activities == null))
                {
                    this._Activities = Context.CreateQuery<global::Ch.Abacus.Worx.Activity>(GetPath("Activities"));
                }
                return this._Activities;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Ch.Abacus.Worx.Activity> _Activities;
    }
    /// <summary>
    /// A subject which can either be an organisation or a natural person
    /// </summary>
    /// <KeyProperties>
    /// AddressNumber
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("AddressNumber")]
    [global::Microsoft.OData.Client.HasStream()]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Address")]
    public partial class Address : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="addressNumber">Initial value of AddressNumber.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="struct">Initial value of Struct.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Address CreateAddress(long addressNumber, string lastName, global::Ch.Abacus.Worx.SubjectType type, global::Ch.Abacus.Worx.Struct @struct)
        {
            Address address = new Address();
            address.AddressNumber = addressNumber;
            address.LastName = lastName;
            address.Type = type;
            if ((@struct == null))
            {
                throw new global::System.ArgumentNullException("@struct");
            }
            address.Struct = @struct;
            return address;
        }
        /// <summary>
        /// There are no comments for Property AddressNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AddressNumber")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AddressNumber is required.")]
        public virtual long AddressNumber
        {
            get
            {
                return this._AddressNumber;
            }
            set
            {
                this.OnAddressNumberChanging(value);
                this._AddressNumber = value;
                this.OnAddressNumberChanged();
                this.OnPropertyChanged("AddressNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _AddressNumber;
        partial void OnAddressNumberChanging(long value);
        partial void OnAddressNumberChanged();
        /// <summary>
        /// First name of the subject may be null for organisations
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FirstName")]
        [global::System.ComponentModel.DataAnnotations.StringLengthAttribute(50, ErrorMessage = "FirstName cannot be longer than 50 characters.")]
        public virtual string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LastName")]
        [global::System.ComponentModel.DataAnnotations.StringLengthAttribute(100, ErrorMessage = "LastName cannot be longer than 100 characters.")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LastName is required.")]
        public virtual string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Type")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Type is required.")]
        public virtual global::Ch.Abacus.Worx.SubjectType Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Ch.Abacus.Worx.SubjectType _Type;
        partial void OnTypeChanging(global::Ch.Abacus.Worx.SubjectType value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Struct in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("struct")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Struct is required.")]
        public virtual global::Ch.Abacus.Worx.Struct Struct
        {
            get
            {
                return this._Struct;
            }
            set
            {
                this.OnStructChanging(value);
                this._Struct = value;
                this.OnStructChanged();
                this.OnPropertyChanged("struct");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Ch.Abacus.Worx.Struct _Struct;
        partial void OnStructChanging(global::Ch.Abacus.Worx.Struct value);
        partial void OnStructChanged();
        /// <summary>
        /// There are no comments for Property Activities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Activities")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Ch.Abacus.Worx.Activity> Activities
        {
            get
            {
                return this._Activities;
            }
            set
            {
                this.OnActivitiesChanging(value);
                this._Activities = value;
                this.OnActivitiesChanged();
                this.OnPropertyChanged("Activities");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Ch.Abacus.Worx.Activity> _Activities = new global::Microsoft.OData.Client.DataServiceCollection<global::Ch.Abacus.Worx.Activity>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnActivitiesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Ch.Abacus.Worx.Activity> value);
        partial void OnActivitiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Struct in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("struct")]
    public partial class Struct : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Struct object.
        /// </summary>
        /// <param name="complexFirstname">Initial value of ComplexFirstname.</param>
        /// <param name="complexLastname">Initial value of ComplexLastname.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Struct CreateStruct(string complexFirstname, string complexLastname)
        {
            Struct @struct = new Struct();
            @struct.ComplexFirstname = complexFirstname;
            @struct.ComplexLastname = complexLastname;
            return @struct;
        }
        /// <summary>
        /// There are no comments for Property ComplexFirstname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ComplexFirstname")]
        [global::System.ComponentModel.DataAnnotations.StringLengthAttribute(20, ErrorMessage = "ComplexFirstname cannot be longer than 20 characters.")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ComplexFirstname is required.")]
        public virtual string ComplexFirstname
        {
            get
            {
                return this._ComplexFirstname;
            }
            set
            {
                this.OnComplexFirstnameChanging(value);
                this._ComplexFirstname = value;
                this.OnComplexFirstnameChanged();
                this.OnPropertyChanged("ComplexFirstname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ComplexFirstname;
        partial void OnComplexFirstnameChanging(string value);
        partial void OnComplexFirstnameChanged();
        /// <summary>
        /// There are no comments for Property ComplexLastname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ComplexLastname")]
        [global::System.ComponentModel.DataAnnotations.StringLengthAttribute(20, ErrorMessage = "ComplexLastname cannot be longer than 20 characters.")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ComplexLastname is required.")]
        public virtual string ComplexLastname
        {
            get
            {
                return this._ComplexLastname;
            }
            set
            {
                this.OnComplexLastnameChanging(value);
                this._ComplexLastname = value;
                this.OnComplexLastnameChanged();
                this.OnPropertyChanged("ComplexLastname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ComplexLastname;
        partial void OnComplexLastnameChanging(string value);
        partial void OnComplexLastnameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SubjectType in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SubjectType")]
    public enum SubjectType
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Person")]
        Person = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Organisation")]
        Organisation = 2
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Ch.Abacus.Worx.Activity as global::Ch.Abacus.Worx.ActivitySingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Ch.Abacus.Worx.ActivitySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Ch.Abacus.Worx.Activity> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Ch.Abacus.Worx.ActivitySingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Ch.Abacus.Worx.Activity as global::Ch.Abacus.Worx.ActivitySingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="activityKey">The value of activityKey</param>
        public static global::Ch.Abacus.Worx.ActivitySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Ch.Abacus.Worx.Activity> _source,
            global::System.Guid activityKey)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ActivityKey", activityKey }
            };
            return new global::Ch.Abacus.Worx.ActivitySingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Ch.Abacus.Worx.Address as global::Ch.Abacus.Worx.AddressSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Ch.Abacus.Worx.AddressSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Ch.Abacus.Worx.Address> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Ch.Abacus.Worx.AddressSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Ch.Abacus.Worx.Address as global::Ch.Abacus.Worx.AddressSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="addressNumber">The value of addressNumber</param>
        public static global::Ch.Abacus.Worx.AddressSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Ch.Abacus.Worx.Address> _source,
            long addressNumber)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "AddressNumber", addressNumber }
            };
            return new global::Ch.Abacus.Worx.AddressSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
namespace Ch.Abacus.Adre
{
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
    }
}
namespace Ch.Abacus.Odata
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ch.abacus.odata", "Ch.Abacus.Odata");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "ch.abacus.adre", "Ch.Abacus.Adre");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "ch.abacus.worx", "Ch.Abacus.Worx");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Ch.Abacus.Odata", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("ch.abacus.odata.", originalNameAttribute.OriginalName);
                }
                return string.Concat("ch.abacus.odata.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Ch.Abacus.Adre", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("ch.abacus.adre.", originalNameAttribute.OriginalName);
                }
                return string.Concat("ch.abacus.adre.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Ch.Abacus.Worx", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("ch.abacus.worx.", originalNameAttribute.OriginalName);
                }
                return string.Concat("ch.abacus.worx.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for AddressesStub in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AddressesStub")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Ch.Abacus.Worx.Address> AddressesStub
        {
            get
            {
                if ((this._AddressesStub == null))
                {
                    this._AddressesStub = base.CreateQuery<global::Ch.Abacus.Worx.Address>("AddressesStub");
                }
                return this._AddressesStub;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Ch.Abacus.Worx.Address> _AddressesStub;
        /// <summary>
        /// There are no comments for ActivitiesStub in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ActivitiesStub")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Ch.Abacus.Worx.Activity> ActivitiesStub
        {
            get
            {
                if ((this._ActivitiesStub == null))
                {
                    this._ActivitiesStub = base.CreateQuery<global::Ch.Abacus.Worx.Activity>("ActivitiesStub");
                }
                return this._ActivitiesStub;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Ch.Abacus.Worx.Activity> _ActivitiesStub;
        /// <summary>
        /// There are no comments for AddressesStub in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToAddressesStub(global::Ch.Abacus.Worx.Address address)
        {
            base.AddObject("AddressesStub", address);
        }
        /// <summary>
        /// There are no comments for ActivitiesStub in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToActivitiesStub(global::Ch.Abacus.Worx.Activity activity)
        {
            base.AddObject("ActivitiesStub", activity);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"OData ServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
